const actionTypes = Object.freeze({
    //app
    APP_START_UP_COMPLETE: 'APP_START_UP_COMPLETE',
    SET_CONTENT_OF_CONFIRM_MODAL: 'SET_CONTENT_OF_CONFIRM_MODAL',
    CHANGE_LANGUAGE: 'CHANGE_LANGUAGE',
    //user
    ADD_USER_SUCCESS: 'ADD_USER_SUCCESS',
    USER_LOGIN_SUCCESS: 'USER_LOGIN_SUCCESS',
    USER_LOGIN_FAIL: 'USER_LOGIN_FAIL',
    PROCESS_LOGOUT: 'PROCESS_LOGOUT',

    //admin
    GET_ALL_USER_SUCCESS: 'GET_ALL_USER_SUCCESS',
    GET_ALL_USER_FAILED: 'GET_ALL_USER_FAILED',
    //Gender
    FETCH_GENDER_SUCCESS: 'FETCH_GENDER_SUCCESS',
    FETCH_GENDER_FAILED: 'FETCH_GENDER_FAILED',

    //Role
    FETCH_ROLE_SUCCESS: 'FETCH_ROLE_SUCCESS',
    FETCH_ROLE_FAILED: 'FETCH_ROLE_FAILED',
    //Month
    FETCH_MONTH_SUCCESS: 'FETCH_MONTH_SUCCESS',
    FETCH_MONTH_FAILED: 'FETCH_MONTH_FAILED',
    //Room
    GET_ALL_ROOM_SUCCESS: 'GET_ALL_ROOM_SUCCESS',
    GET_ALL_ROOM_FAILED: 'GET_ALL_ROOM_FAILED',
    //Status
    GET_STATUS_DEVICE_SUCCESS: 'GET_STATUS_DEVICE_SUCCESS',
    GET_STATUS_DEVICE_FAILED: 'GET_STATUS_DEVICE_FAILED',
    //Status
    GET_TYPE_DEVICE_SUCCESS: 'GET_TYPE_DEVICE_SUCCESS',
    GET_TYPE_DEVICE_FAILED: 'GET_TYPE_DEVICE_FAILED',
    //Device
    GET_ALL_DEVICE_SUCCESS: 'GET_ALL_DEVICE_SUCCESS',
    GET_ALL_DEVICE_FAILED: 'GET_ALL_DEVICE_FAILED',

    CREAT_USER_SUCCESS: 'CREAT_USER_SUCCESS',
    CREAT_USER_FAILED: 'CREAT_USER_FAILED',

    DELETE_USER_SUCCESS: 'DELETE_USER_SUCCESS',
    DELETE_USER_FAILED: 'DELETE_USER_FAILED',

    EDIT_USER_SUCCESS: 'EDIT_USER_SUCCESS',
    EDIT_USER_FAILED: 'EDIT_USER_FAILED',

    FETCH_TOP_DOCTOR_SUCCESS: 'FETCH_TOP_DOCTOR_SUCCESS',
    FETCH_TOP_DOCTOR_FAILED: 'FETCH_TOP_DOCTOR_FAILED',

    FETCH_ALL_DOCTOR_SUCCESS: 'FETCH_ALL_DOCTOR_SUCCESS',
    FETCH_ALL_DOCTOR_FAILED: 'FETCH_ALL_DOCTOR_FAILED',

    UPDATE_INFOR_DOCTOR_SUCCESS: 'UPDATE_INFOR_DOCTOR_SUCCESS',
    UPDATE_INFOR_DOCTOR_FAILED: 'UPDATE_INFOR_DOCTOR_FAILED',

    FETCH_ALLCODE_SCHEDULE_TIME_SUCCESS: 'FETCH_ALLCODE_SCHEDULE_TIME_SUCCESS',
    FETCH_ALLCODE_SCHEDULE_TIME_FAILED: 'FETCH_ALLCODE_SCHEDULE_TIME_FAILED',

    FETCH_ALL_SPECIALTY_SUCCESS: 'FETCH_ALL_SPECIALTY_SUCCESS',
    FETCH_ALL_SPECIALTY_FAILED: 'FETCH_ALL_SPECIALTY_FAILED',

    FETCH_ALL_CLINIC_SUCCESS: 'FETCH_ALL_CLINIC_SUCCESS',
    FETCH_ALL_CLINIC_FAILED: 'FETCH_ALL_CLINIC_FAILED',

    FETCH_TOP_CLINIC_SUCCESS: 'FETCH_TOP_CLINIC_SUCCESS',
    FETCH_TOP_CLINIC_FAILED: 'FETCH_TOP_CLINIC_FAILED',

    FETCH_PROMOTION_KEY_SUCCESS: 'FETCH_PROMOTION_KEY_SUCCESS',
    FETCH_PROMOTION_KEY_FAILED: 'FETCH_PROMOTION_KEY_FAILED',

    FETCH_ALL_PROMOTION_SUCCESS: 'FETCH_ALL_PROMOTION_SUCCESS',
    FETCH_ALL_PROMOTION_FAILED: 'FETCH_ALL_PROMOTION_FAILED',

    CHANGE_STATUS_REACT_LOADING: 'CHANGE_STATUS_REACT_LOADING',
});
export default actionTypes;
